apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"godaddy-ddns-cronjob","namespace":"godaddy-ddns"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"metadata":{"labels":{"app":"cron-godaddy-ddns"}},"spec":{"template":{"spec":{"containers":[{"env":[{"name":"KEY","valueFrom":{"secretKeyRef":{"key":"key","name":"godaddy-secret"}}},{"name":"SECRET","valueFrom":{"secretKeyRef":{"key":"secret","name":"godaddy-secret"}}}],"image":"gabecamp/harpi:godaddy-ddns","name":"godaddy-ddns-container"}],"restartPolicy":"Never"}}}},"schedule":"1 * * * *","successfulJobsHistoryLimit":3}}
    creationTimestamp: "2020-03-01T16:05:12Z"
    name: godaddy-ddns-cronjob
    namespace: godaddy-ddns
    resourceVersion: "63702818"
    selfLink: /apis/batch/v1beta1/namespaces/godaddy-ddns/cronjobs/godaddy-ddns-cronjob
    uid: 6ec29337-5bd6-11ea-9409-b827ebcf11db
  spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
        labels:
          app: cron-godaddy-ddns
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
            - env:
              - name: KEY
                valueFrom:
                  secretKeyRef:
                    key: key
                    name: godaddy-secret
              - name: SECRET
                valueFrom:
                  secretKeyRef:
                    key: secret
                    name: godaddy-secret
              image: gabecamp/harpi:godaddy-ddns
              imagePullPolicy: IfNotPresent
              name: godaddy-ddns-container
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: 1 * * * *
    successfulJobsHistoryLimit: 3
    suspend: false
  status:
    lastScheduleTime: "2020-04-19T01:01:00Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
